services:
    ### Message Handlers and Scheduled Tasks ###

    Klaviyo\Integration\Async\Task\ScheduleEventJobsTask:
        tags:
            - { name: 'shopware.scheduled.task' }

    Klaviyo\Integration\Async\TaskHandler\ScheduleEventJobsHandler:
        arguments:
            - '@scheduled_task.repository'
            - '@Klaviyo\Integration\Model\UseCase\ScheduleBackgroundJob'
        tags:
            - { name: 'messenger.message_handler' }

    ### Operations' definitions ###

    Klaviyo\Integration\Model\UseCase\Operation\EventsProcessingOperation:
        tags:
            - { name: 'od.job_handler', code: 'od-klaviyo-events-sync-handler' }
        arguments:
            - '@klaviyo_job_event.repository'
            - '@klaviyo_job_cart_request.repository'
            - '@Klaviyo\Integration\Model\UseCase\ScheduleBackgroundJob'

    Klaviyo\Integration\Model\UseCase\Operation\CartEventSyncOperation:
        tags:
            - { name: 'od.job_handler', code: 'od-klaviyo-cart-event-sync-handler' }
        arguments:
            - '@Klaviyo\Integration\System\Tracking\EventsTracker'
            - '@klaviyo_job_cart_request.repository'
            - '@Klaviyo\Integration\Model\CartRequestSerializer'

    Klaviyo\Integration\Model\UseCase\Operation\FullOrderSyncOperation:
        tags:
            - { name: 'od.job_handler', code: 'od-klaviyo-full-order-sync-handler' }
        arguments:
            - '@Klaviyo\Integration\Model\UseCase\ScheduleBackgroundJob'
            - '@order.repository'
            - '@Od\Scheduler\Model\MessageManager'

    Klaviyo\Integration\Model\UseCase\Operation\FullSubscriberSyncOperation:
        tags:
            - { name: 'od.job_handler', code: 'od-klaviyo-full-subscriber-sync-handler' }
        arguments:
            - '@Klaviyo\Integration\Model\UseCase\ScheduleBackgroundJob'
            - '@newsletter_recipient.repository'

    Klaviyo\Integration\Model\UseCase\Operation\OrderEventsSyncOperation:
        tags:
            - { name: 'od.job_handler', code: 'od-klaviyo-order-event-sync-handler' }
        arguments:
            - '@klaviyo_job_event.repository'
            - '@order.repository'
            - '@Klaviyo\Integration\System\Tracking\EventsTracker'
            - '@Od\Scheduler\Model\MessageManager'

    Klaviyo\Integration\Model\UseCase\Operation\OrderSyncOperation:
        tags:
            - { name: 'od.job_handler', code: 'od-klaviyo-order-sync-handler' }
        arguments:
            - '@order.repository'
            - '@Klaviyo\Integration\System\Tracking\EventsTracker'
            - '@Od\Scheduler\Model\MessageManager'

    Klaviyo\Integration\Model\UseCase\Operation\SubscriberSyncOperation:
        tags:
            - { name: 'od.job_handler', code: 'od-klaviyo-subscriber-sync-handler' }
        arguments:
            - '@Klaviyo\Integration\Klaviyo\Gateway\KlaviyoGateway'
            - '@Klaviyo\Integration\Configuration\ConfigurationRegistry'
            - '@newsletter_recipient.repository'
            - '@sales_channel.repository'
