services:
    Klaviyo\Integration\Klaviyo\Gateway\ClientRegistry:
        arguments:
            - '@Klaviyo\Integration\Klaviyo\Client\ClientFactory'
            - '@Klaviyo\Integration\Klaviyo\Gateway\ClientConfigurationFactory'

    Klaviyo\Integration\Klaviyo\Gateway\ClientConfigurationFactory:
        arguments:
            - '@Klaviyo\Integration\Configuration\ConfigurationRegistry'

    Klaviyo\Integration\Klaviyo\Client\ClientFactory:
        arguments:
            - '@Klaviyo\Integration\Klaviyo\Client\ApiTransfer\Translator\TranslatorsRegistryFactory'
            - '@klaviyo.tracking_integration.guzzle_client'

    Klaviyo\Integration\Klaviyo\Client\ApiTransfer\Translator\TranslatorsRegistryFactory:
        arguments:
            - '@Klaviyo\Integration\Klaviyo\Client\Serializer\SerializerFactory'

    klaviyo.tracking_integration.guzzle_client:
        class: GuzzleHttp\Client

    Klaviyo\Integration\Klaviyo\Client\Serializer\SerializerFactory: ~