services:
    Klaviyo\Integration\Entity\Event\EventDefinition:
        tags:
            - { name: 'shopware.entity.definition', entity: 'klaviyo_job_event' }

    Klaviyo\Integration\Entity\CartRequest\CartRequestDefinition:
        tags:
            - { name: 'shopware.entity.definition', entity: 'klaviyo_job_cart_request' }
