services:
    Klaviyo\Integration\Klaviyo\Gateway\KlaviyoGateway:
        arguments:
            - '@Klaviyo\Integration\Klaviyo\Gateway\ClientRegistry'
            - '@Klaviyo\Integration\Klaviyo\Gateway\Translator\OrderEventRequestTranslator'
            - '@Klaviyo\Integration\Klaviyo\Gateway\Translator\ProductEventRequestTranslator'
            - '@Klaviyo\Integration\Klaviyo\Gateway\Translator\CartEventRequestTranslator'
            - '@Klaviyo\Integration\Klaviyo\Gateway\Translator\SubscribersToKlaviyoRequestsTranslator'
            - '@Klaviyo\Integration\Klaviyo\Gateway\Translator\IdentifyProfileRequestTranslator'
            - '@logger'

    Klaviyo\Integration\Klaviyo\Gateway\Translator\OrderEventRequestTranslator:
        arguments:
            - '@product.repository'
            - '@order_address.repository'
            - '@order_delivery.repository'
            - '@order_line_item.repository'
            - '@Klaviyo\Integration\Entity\Helper\AddressDataHelper'
            - '@Klaviyo\Integration\Entity\Helper\ProductDataHelper'
            - '@Klaviyo\Integration\Klaviyo\Gateway\Translator\CustomerPropertiesTranslator'

    Klaviyo\Integration\Klaviyo\Gateway\Translator\IdentifyProfileRequestTranslator:
        arguments:
            - '@Klaviyo\Integration\Klaviyo\Gateway\Translator\CustomerPropertiesTranslator'

    Klaviyo\Integration\Klaviyo\Gateway\Translator\ProductEventRequestTranslator:
        arguments:
            - '@Klaviyo\Integration\Klaviyo\Gateway\Translator\CustomerPropertiesTranslator'
            - '@Klaviyo\Integration\Entity\Helper\ProductDataHelper'

    Klaviyo\Integration\Klaviyo\Gateway\Translator\CustomerPropertiesTranslator:
        arguments:
            - '@Klaviyo\Integration\Entity\Helper\AddressDataHelper'

    Klaviyo\Integration\Klaviyo\Gateway\Translator\CartEventRequestTranslator:
        arguments:
            - '@Klaviyo\Integration\Klaviyo\Gateway\Translator\CustomerPropertiesTranslator'
            - '@Klaviyo\Integration\Entity\Helper\ProductDataHelper'
            - '@router.default'

    Klaviyo\Integration\Klaviyo\Gateway\Translator\SubscribersToKlaviyoRequestsTranslator: ~
