parameters:
    klaviyo.tracking_integration.subscribers_synchronization.job.maximum_pending_time: 20
    klaviyo.tracking_integration.subscribers_synchronization.job.maximum_execution_time: 180

services:
    klaviyo.tracking_integration.subscribers_synchronization.job.scheduler:
        parent: klaviyo.tracking_integration.job.scheduler.configurable
        arguments:
            - '@klaviyo.tracking_integration.subscribers_synchronization.job.stuck.specification'
            - 'subscribers_synchronization'
        tags:
            - { name: klaviyo.tracking_integration.job.scheduler }

    klaviyo.tracking_integration.subscribers_synchronization.job.stuck.specification:
        class: Klaviyo\Integration\Entity\Specification\StuckJobSpecification
        arguments:
            - '%klaviyo.tracking_integration.subscribers_synchronization.job.maximum_pending_time%'
            - '%klaviyo.tracking_integration.subscribers_synchronization.job.maximum_execution_time%'

    Klaviyo\Integration\Subscriber\Job\FullResynchronizationJobProcessor:
        arguments:
            - '@Klaviyo\Integration\Klaviyo\Gateway\KlaviyoGateway'
            - '@sales_channel.repository'
            - '@newsletter_recipient.repository'
            - '@Klaviyo\Integration\Entity\Helper\JobHelper'
            - '@Klaviyo\Integration\Configuration\ConfigurationRegistry'
            - '@logger'
        tags:
            - { name: klaviyo.tracking_integration.job.processor }

    Klaviyo\Integration\Async\SubscribersSynchronizationScheduledTask:
        tags:
            - { name: 'shopware.scheduled.task' }

    Klaviyo\Integration\Async\SubscribersSynchronizationScheduledTaskHandler:
        arguments:
            - '@scheduled_task.repository'
            - '@Klaviyo\Integration\Entity\Helper\JobHelper'
            - '@Klaviyo\Integration\Job\VirtualProxyJobScheduler'
            - '@Klaviyo\Integration\Configuration\ConfigurationRegistry'
            - '@klaviyo.tracking_integration.subscribers_synchronization.job.stuck.specification'
            - '@logger'
        tags:
            - { name: 'messenger.message_handler' }
